"""empty message

Revision ID: fe001df8825b
Revises: f379cff0299c
Create Date: 2025-08-02 04:11:38.235664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe001df8825b'
down_revision = 'f379cff0299c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'personaje', ['personaje_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personaje_id')

    # ### end Alembic commands ###
